</main>
<footer>
    <div class="container text-white d-flex align-items-center justify-content-between">
        <a id="logo1" href="#"><img src="https://tyrolium.fr/Contenu/Image/Tyrolium%20Site.png" alt="logo-tyrolium"></a>
        <span>2017-2024 © <a href="https://tyrolium.fr/">TYROLIUM</a><br>Create by Maxime Tournier</span>
        <button onclick="window.location.href = 'https://stats.uptimerobot.com/7z9o3SEnWX';" type="button" class="btn btn-primary">Ping</button>
    </div>
</footer>

<style>

    footer {
        background-color: #303030;
        border-top: 10px solid;
        border-color: #375a7f;
        padding: 40px 0 50px;
        margin-top: 100px;
    }
    footer span{
        text-align: center;
    }
    footer img {
        width: 70px;
    }

    footer a{
        color: white;
    }

    footer a:hover{
        color: white;
    }

</style>