<div id="header">


    <div class="text">

        <h1><span>SolidServ</span> Uptime</h1>
        <h2>SolidServ est une fillaire de Tyrolium qui héberge des serveur informatique </h2>

    </div>

</div>

<style>
    #header{

        height: 500px;
        text-align: center;
        background-image: url("https://www.usinenouvelle.com/mediatheque/2/1/6/000565612_896x598_c.jpg");

        display: flex;
        align-items: center; /* Centrer verticalement */
        justify-content: center;
    }



    #header .text{

    }




</style>