<meta charset="UTF-8">
<title>Tyrolium Uptime</title>
<link href="https://tyrolium.fr/Contenu/Image/Tyrolium Site.png" rel="shortcut icon">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://bootswatch.com/5/darkly/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<meta name="title" content="Tyrolium Uptime">
<meta name="description" content="Site sur L'infrastructure réseau de Tyrolium"/>
<meta property="og:title" content="Tyrolium Uptime"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://tyrolium.fr/uptime/"/>
<meta property="og:image" content="https://tyrolium.fr/Contenu/Image/Tyrolium Site.png"/>
<meta property="og:description" content="Site sur L'infrastructure réseau de Tyrolium"/>