<header>
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
        <div class="container-fluid justify-content-center">
            <a class="navbar-brand" href="#">
                <img src="https://tyrolium.fr/Contenu/Image/Tyrolium%20Site.png" alt="Logo" width="30"  class="d-inline-block align-text-top">
                Tyrolium Uptime
            </a>
        </div>
    </nav>
</header>

<style>

    nav {
        background-color: #303030!important;
        border-bottom: 10px solid;
        border-color: #375a7f;
    }

</style>