<header>
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
        <div class="container-fluid justify-content-center">
            <a class="navbar-brand" href="#">
                <img src="https://tyrolium.fr/Contenu/Image/Tyrolium%20Site.png" alt="Logo" width="30"  class="d-inline-block align-text-top">
                Tyrolium Uptime
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>
</header>

<style>

    nav {
        background-color: #303030!important;
        border-bottom: 10px solid;
        border-color: #375a7f;
    }

</style>