<div class="card-serv">

    <div class="container-Icone">

        <?php if ($status == "onl2ine") {
            echo ' <p class="overlay-status-Icone d-inline-flex mb-3 px-2 py-1 fw-semibold text-success-emphasis bg-success-subtle border border-success-subtle rounded-2"><i class="fa-solid fa-signal" style="margin-top: 4px;margin-right: 5px;"></i> En ligne </p>';
        } else {
            echo '<p class="overlay-status-Icone d-inline-flex mb-3 px-2 py-1 fw-semibold text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-2"><i class="fa-solid fa-power-off" style="margin-top: 4px;margin-right: 5px;"></i> Hors ligne </p>';
        } ?>

        <img class="main-image-Icone card-img-top" src="assets/<?= $server['group'] ?>.png" alt="Image Group"
        <?php if ($server['tag']){ echo '><img class="overlay-image-Icone" src="assets/projet/'. $server['tag'] .'.png" alt="Image Projet">';} else { echo 'style="margin-left: 12px;">'; } ?>
    </div>
    <div class="card-body">
        <div class="card-name-display">
            <h5 class="card-title"><?= $server['name'] ?></h5>
            <?php if ($server['alias']){ ?><small>alias : <?= $server['alias'] ?></small><?php } ?>
        </div>

        <p class="card-text" style="margin-bottom: unset">
            <i class="fa-solid fa-location-dot"></i> Lieu : <br>
            <p style="text-align: center"><?= $server['lieu'] ?></p>
        </p>
        <p class="card-text" style="margin-bottom: unset">
            <i class="fa-solid fa-calendar"></i> Date de mise en service : <br>
            <p style="text-align: center"><?= $server['date'] ?></p>
        </p>

        <p class="card-text" style="margin-bottom: unset">
            <i class="fa-solid fa-comment"></i> Description : <br>
            <small>&ensp;&ensp;<?= $server['description'] ?></small>
        </p>

        <a href="http://<?= $server['url'] ?>" class="btn btn-primary btn-server">Host Link</a>
    </div>
</div>



<style>
    txC{
        text-align: center;
    }
    .card-body i{
        margin-right: 5px;
        color: #42658d;
    }

    .card-name-display{
        margin-bottom: 12px;
    }

    .btn-server{
        position: absolute;
        bottom: 12px;
        left: 12px;
        width: 91%;
    }

    .card-serv{
        background-color: #303030;
        padding: 20px;
            display: flex;
            flex-direction: column;
            position: relative;
            width: 290px;
            height: 550px;
            box-shadow: -1px 15px 30px -12px rgb(32, 32, 32);
            border-radius: 0.9rem;

            cursor: pointer;
            margin: 20px 20px 20px 10px;
            transition: transform 0.2s ease-out;
            will-change: transform;

    }

    .card-serv:hover{
        transform: scale(1.05);
    }

    .container-Icone {
        position: relative;
        width: 300px; /* Ajustez la largeur selon vos besoins */
        height: 225px; /* Ajustez la hauteur selon vos besoins */
    }

    .main-image-Icone {
        width: 225px;
        height: 225px;
        object-fit: cover; /* Ajuste la taille de l'image pour remplir la div */
    }

    .overlay-image-Icone {
        position: absolute;
        bottom: 10px;
        right: 49px;
        width: 72px;
    }
    .overlay-status-Icone {
        position: absolute;
        top: -6px;
        right: 36px;
        transform: scale(0.9);
    }
</style>