<main>
    <div class="info-start">

        <p>
            <strong>A quoi sert ce site :</strong>

            vous pouvez consulter l'infractructur réseau de Tyrolium et ces fillaire, notamment SolidServ fillaire dans le domaine du serveur, mais aussi TyroServ, Gamenium et bien d'autre

        </p>
    </div>

<style>

    .info-start{
        margin: 40px;
        background-color: #303030;
    }

    .info-start p{

        border-left: solid #797979;
        padding: 42px;
    }


</style>