<main>
    <div class="info-start">

        <p>
            <strong>À quoi sert ce site :</strong>

            Ce site vous permet de consulter l'infrastructure réseau de Tyrolium et de ses filiales, notamment SolidServ, filiale spécialisée dans les serveurs, ainsi que TyroServ, Gamenium et bien d'autres.

        </p>
    </div>

<style>

    .info-start{
        margin: 40px;
        background-color: #303030;
    }

    .info-start p{

        border-left: solid #797979;
        padding: 42px;
    }


</style>